import type { Metadata } from "next";
import ThemeProvider from "@/components/provider/theme-provider";
import "./globals.css";

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <>
      <html lang="en" suppressHydrationWarning >
        <body className="antialiased bg-background-light dark:bg-background-dark">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            // enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}

export default RootLayout;
export {
  metadata
};
